# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory
WORKDIR /usr/src/app

# Copy the requirements file into the container
COPY Backend/requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir
