version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9  # Use a CircleCI image with Python
    working_directory: ~/app

    steps:
      - checkout

      # Frontend Build
      - run:
          name: Install Frontend Dependencies
          command: |
            cd Frontend
            npm install

      - run:
          name: Build Frontend
          command: |
            cd Frontend
            npm run build

      # Backend Build
      - run:
          name: Install Backend Dependencies
          command: |
            cd Backend
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install -r requirements.txt

  deploy:
    docker:
      - image: cimg/python:3.9  # Use a CircleCI image with Python
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Deploy to Heroku
          command: |
            echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com
            heroku container:login
            docker build -t registry.heroku.com/strangefront/web Frontend
            docker push registry.heroku.com/strangefront/web
            heroku container:release web -a strangefront

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
