version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.0  # Node.js image for building Angular app
      - image: cimg/python:3.9  # Python image for building FastAPI app

    steps:
      - checkout

      # Frontend Build
      - run:
          name: Install Frontend Dependencies
          command: |
            cd Frontend
            npm install

      - run:
          name: Build Frontend
          command: |
            cd Frontend
            npm run build

      # Backend Build
      - run:
          name: Install Backend Dependencies
          command: |
            cd Backend

            # Install pip for Python 3 using sudo
            sudo apt-get update
            sudo apt-get install -y python3-pip

            # Now, install the requirements
            pip3 install -r requirements.txt

  deploy:
    docker:
      - image: heroku/heroku:18  # Heroku CLI image

    steps:
      - checkout

      - heroku/deploy-via-git:
          app: strangefront
          requires:
            - build

      - heroku/deploy-via-git:
          app: strangeback
          requires:
            - build
