version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Build and push Docker image
          command: |
            docker build -t your-heroku-app-name .
            docker login -u $HEROKU_REGISTRY_USER -p $HEROKU_API_KEY registry.heroku.com
            docker tag your-heroku-app-name registry.heroku.com/your-heroku-app-name/web
            docker push registry.heroku.com/your-heroku-app-name/web

      - deploy:
          name: Deploy to Heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:release web -a your-heroku-app-name
