version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.0  # Node.js image for building Angular app
      - image: cimg/python:3.9  # Python image for building FastAPI app

    steps:
      - checkout

      # Frontend Build
      - run:
          name: Install Frontend Dependencies
          command: |
            cd Frontend
            npm install

      - run:
          name: Build Frontend
          command: |
            cd Frontend
            npm run build

      # Backend Build
      - run:
          name: Install Backend Dependencies
          command: |
            cd Backend
            pip3 install -r requirements.txt

  deploy:
    docker:
      - image: heroku/heroku:18  # Heroku CLI image

    steps:
      - checkout

      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Deploy Frontend to Heroku
          command: |
            heroku container:login
            heroku container:push web -a strangefront
            heroku container:release web -a strangefront

      - run:
          name: Deploy Backend to Heroku
          command: |
            heroku container:login
            heroku container:push web -a strangeback
            heroku container:release web -a strangeback

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

