version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Update to Python 3.9

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Build and push Docker image
          command: |
            docker build -t $HEROKU_REGISTRY_USER/strrange .
            docker login -u $HEROKU_REGISTRY_USER -p $HEROKU_API_KEY registry.heroku.com
            docker tag $HEROKU_REGISTRY_USER/strrange registry.heroku.com/strrange/web
            docker push registry.heroku.com/strrange/web

      - deploy:
          name: Deploy to Heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:release web -a strrange  # Use the actual Heroku app name
